### ISSUE TITLE
Including elastase for msgfplus

### ISSUE THREAD

**Issue by cguetot** [ursgal/ursgal#116]
Hi guys,

I know Ursgal doesn't include **elastase** for **Msgfplus**.  However, starting from version **v2019.02.07**, there was included support for customizing enzyme definitions. We need to create file `params\enzymes.txt` (or `params/enzymes.txt` on Linux) below the working directory to define custom enzymes or override the cleavage residues for built-in enzymes.

The format of the `enzymes.txt` is defined here:  https://msgfplus.github.io/msgfplus/examples/enzymes.txt

I wonder how we can work around this information to include support for elastase.

best,

Carlos

_source_: https://msgfplus.github.io/msgfplus/Changelog.html

**Comment by StSchulze** [comment]
Oh nice, thanks for pointing us to this. I was always a bit annoyed by the limited choices of enzyme cleavage for MS-GF+.
It would be fairly easy to make that change since it would just require writing the enzymes.txt (which can be easily included in the msgfplus wrapper, some engines do that already, e.g. msamanda) and changing the uvalue_translation in uparams (probably with a new translation style).

I am unfortunately quite busy at the moment, but would be happy to make that change later (potentially next week) - but maybe someone wants to tackle it earlier?

**Comment by StSchulze** [comment]
Hi Carlos,
sorry, this got lost somehow. It was implemented in the dev branch for quite a while and has now finally been merged into the master as well. We have added a couple of enzymes already (and ship the enzymes.txt as included in the msgfplus version installed through download_resources) but let us know if you need more.
But for elastase you can now specify it through the ursgal params, e.g.:
`uc = ursgal.UController()`
`uc.params['enzyme'] = 'elastase'`

I'll close this for now but feel free to re-open with any questions.
