### ISSUE TITLE
do_it_all_folder crashes with example_data

### ISSUE THREAD

**Issue by wolski** [ursgal/ursgal#13]
I use the data from the example_data folder to run the do_it_all_folder script. It does crash with a percolator error.

Percolator terminates with:

Error in the input data: to good separation between target and decoy PSMs.
Impossible to estimate pi0. Terminating.

Ursgal reports:

AssertionError: 
percolator_2_08 crashed!

Should in such case the entire workflow crash? Or should it handle this particular error more gracefully? e.g. still produce a result.

Selected feature number 0 as initial search direction, could separate -1 positives in that direction
Selected feature number 0 as initial search direction, could separate -1 positives in that direction
Selected feature number 0 as initial search direction, could separate -1 positives in that direction
Estimating 1 over q=0.01 in initial direction
Reading in data and feature calculation took 0.003 cpu seconds or 0 seconds wall time
---Training with Cpos selected by cross validation, Cneg selected by cross validation, fdr=0.01
Iteration 1 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 2 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 3 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 4 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 5 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 6 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 7 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 8 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 9 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Iteration 10 :	After the iteration step, 1 target PSMs with q<0.01 were estimated by cross validation
Obtained weights (only showing weights of first cross validation set)
# first line contains normalized weights, second line the raw weights
lnrSp	deltLCn	deltCn	Xcorr	Sp	IonFrac	Mass	PepLen	Charge1	Charge2	Charge3	Charge4	Charge5	Charge6	Charge7	Charge8	Charge9	Charge10	enzN	enzC	m0
0	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0909
0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0000	0.0909
After all training done, 1 target PSMs with q<0.0100 were found when measuring on the test set
Found 1 target PSMs scoring over 1.0000% FDR level on testset
Merging results from 3 datasets
Error in the input data: too good separation between target and decoy PSMs.
Impossible to estimate pi0. Terminating.
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/wolski/prog/ursgal2/example_scripts/do_it_all_folder_wide.py", line 124, in <module>
    target_decoy_database = sys.argv[3],
  File "C:/Users/wolski/prog/ursgal2/example_scripts/do_it_all_folder_wide.py", line 100, in main
    engine      = validation_engine,
  File "C:\Users\wolski\prog\ursgal2\ursgal\ucontroller.py", line 2823, in validate
    output_file_name = output_file_name
  File "C:\Users\wolski\prog\ursgal2\ursgal\ucontroller.py", line 2744, in execute_unode
    force, engine_name, answer
  File "C:\Users\wolski\prog\ursgal2\ursgal\ucontroller.py", line 2068, in run_unode_if_required
    json_path = json_path,
  File "C:\Users\wolski\prog\ursgal2\ursgal\unode.py", line 1243, in run
    report['execution'] = self._execute()
  File "C:\Users\wolski\prog\ursgal2\ursgal\unode.py", line 459, in _execute
    '''.format( self.engine, os.path.relpath(self.exe), self.execute_return_code)
AssertionError: 
  
percolator_2_08 crashed!

  The executable
    ..\ursgal\resources\win32\64bit\percolator_2_08\percolator.exe
  terminated with Error code 255 .
  Inspect the printouts above for possible causes and verify that all input files are valid.

**Comment by LKremer** [comment]
Hi,
thanks for the report. The crash occurs since the example dataset that we've included is so tiny that Percolator cannot make sense of it. We chose this file to keep the package size low and to speed up the tests. The downside is that we can't use it to test Percolator, as you have noticed. This problem would not occur with a real dataset.

> Should in such case the entire workflow should crash? Or should it handle this particular error more gracefully?

Good point, in this particular case it would make sense to skip the post-processing step with Percolator and to carry on with the workflow. However, this only works because Percolator is the last step of this workflow. If a UNode at the start of a workflow (e.g. a search engine) crashes, this would cause further crashes downstream. It's hard to predict whether the UNode output is required downstream, so we treat all UNodes equally: If any UNode crashes, the entire workflow is interrupted. This also prevents bugs and confusion due to silent failures.

**Comment by StSchulze** [comment]
If you want to try the workflow with example data you could use the files from the human_br_complete_workflow.

Regarding the handling of the error, I agree with Lukas:
Since we cannot assume a general reason for this error (because it always depends on the users input/workflow) I would not suggest to handle it more gracefully. The user can inspect the error and solve the issue for his case. And if you want to continue in your workflow regardless if an engine crashes, you can just use a try/except loop.
