### ISSUE TITLE
patch version of pymzml dependencies in install_requires

### ISSUE THREAD

**Issue by andy-d-palmer** [ursgal/ursgal#190]
ursgal currently pins the versions of pymzml and pyqms to the patch level in the package install_requires. This is causing me issues trying to install ursgal alongside other packages with different requirements. Could this be relaxed to specify  compatible minor/patch versions?

It might be an idea to have a separate definition of the install_requires which is referenced in setup.py alongside the requirements.txt which is used in the build/test pipeline.

e.g. for patch
pymzml~=2.4
pyqms~=0.6

I'm happy to prepare a PR. What versions of pymzml/pyqms are currently expected to work with ursgal?

**Comment by MKoesters** [comment]
I think we should fix it to minor 2.4, this should work with ursgal and most other software.
Optimal would be 2.5, but since this version is from last month, its possbile that other software using pymzML does not allow this (yet)
For pyQms I need to have a closer look, I'll update my answer once I figured that out
