### ISSUE TITLE
re-ordering of modifications in params triggers re-run

### ISSUE THREAD

**Issue by fu** [ursgal/ursgal#59]
If the same analysis script is re-run with changing the order of the modifications list in params, then re-run is (unnecessarily) triggered.

**Comment by StSchulze** [comment]
Is it only an issue for modifications or for all parameters that er given as lists (e.g. csv_filter_rules as well)?

**Comment by fu** [comment]
good questions, I observed with mods ...

**Comment by LKremer** [comment]
My blind guess would be that [this line in ucontroller.py](https://github.com/ursgal/ursgal/blob/52afd6e1325cfb3c0d47977c6064fd6e05fbe5f7/ursgal/ucontroller.py#L1586) is the issue. If that's the case it should print something like "reason for re-run: "Node related parameters (for instance "modifications") have changed compared to the last output..." to the console, can you confirm?

In that case, the issue should be easy to fix: whenever both params are lists, we perform the "==" evaluation on sorted lists (or sets) instead of the raw lists. However, this would only make sense if there are no params in ursgal that are order-sensitive lists, otherwise we'd introduce a new bug...

**Comment by StSchulze** [comment]
Yes, would have been my guess as well, therefore the question if it occurs for different list params ;)

There are order-sensitive lists, so using sorted lists would surely cause other problems. However, one could change the lists that are not order-sensitive into sets, I guess?

**Comment by LKremer** [comment]
But how do we distinguish between order-sensitive and non-order-sensitive lists? Maybe we need to introduce a new attribute in uparams.py, something like "order-sensitive": True/False?

**Comment by StSchulze** [comment]
No, I meant changing the type of the uparam itself, so "modifications" would be a set of lists.
However, so far we don't have any sets as uparams, so there might be a reason not to do this ...

**Comment by LKremer** [comment]
Yes, the reason is that JSON can't distinguish between sets and lists (there are only arrays). So I think this is unfortunately not possible...

**Comment by StSchulze** [comment]
Ah, right, thanks ... same reason why tuples are not possible ...
Nevertheless, I wouldn't like to introduce another flag for each parameter.
I think the order-sensitive ones are the minority. What about changing them into dictionaries (since each position has a specific meaning)?

**Comment by LKremer** [comment]
You mean like this?
`param = {1: "val1", 2: "val2", 3: "val3"}`
I guess that would work, but we'd break backwards compatability and make it a bit more complicated to specify this parameter.

**Comment by StSchulze** [comment]
Depending on what the positions in the list stand for, it should rather be specific keywords than numbers, but yes, in principle like this.

v0.6.0 is in line and will unforunately break backwards compatibility anyways, so would be a good time to change it ;)

**Comment by StSchulze** [comment]
Should be solved with v0.6.0

**Comment by StSchulze** [comment]
solved with #57
