### ISSUE TITLE
install_requirements fails to download files

### ISSUE THREAD

**Issue by infusini** [ursgal/ursgal#76]
I am trying to run ursgal on my ubuntu EC2 machine on AWS. I am using python3.6.

I get this error when I run `python install_resources.py`:

```
Executable for mzidentml_lib_1_6_11 is not available on your system
[ -<HTPP>- ] Downloading files from http://plan-a.uni-muenster.de/ursgal/resources/platform_independent/arc_independent/mzidentml_lib_1_6_11/mzidentml_lib_1_6_11.md ...
[ -<HTPP>- ] 	 WARNING! Could not download http://plan-a.uni-muenster.de/ursgal/resources/platform_independent/arc_independent/mzidentml_lib_1_6_11/mzidentml_lib_1_6_11.md Check your internet connection!
Traceback (most recent call last):
  File "install_resources.py", line 40, in <module>
    main(resources)
  File "install_resources.py", line 13, in main
    downloaded_zips = uc.download_resources( resources = resources)
  File "/home/ubuntu/ursgal/ursgal/ucontroller.py", line 2727, in download_resources
    'r'
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/ursgal/ursgal/resources/platform_independent/arc_independent/mzidentml_lib_1_6_11/mzidentml_lib_1_6_11.md'
```

I expect the command to install the resources, but obviously it fails. How can I get the command to work?

**Comment by JB-MS** [comment]
Hi,
the resources are currently not available, since we have to move the stuff to another location. We are currently working on a solution for a new location for the resources.

However, you can put the executable manually in the respective folders.E.g. in your case, the folder '/home/ubuntu/ursgal/ursgal/resources/platform_independent/arc_independent/mzidentml_lib_1_6_11/'
should hold all executables for the mzidentml library.

Sorry for the inconvenience.

Cheers,
Johannes

**Comment by fufezan-lab** [comment]
Hi Joe, could we share the resource folder via a private link with Guiseppe
?

Cheers

.c

**Comment by cguetot** [comment]
Hi, 

have

> Hi,
> the resources are currently not available, since we have to move the stuff to another location. We are currently working on a solution for a new location for the resources.
> 
> However, you can put the executable manually in the respective folders.E.g. in your case, the folder '/home/ubuntu/ursgal/ursgal/resources/platform_independent/arc_independent/mzidentml_lib_1_6_11/'
> should hold all executables for the mzidentml library.
> 
> Sorry for the inconvenience.
> 
> Cheers,
> Johannes
> 
> Thanks for using ursgal by the way :)

Dear Johannes,

Do you have a temporal place so we can install and run ursgal properly ?

best

**Comment by StSchulze** [comment]
Hi Carlos,

we have moved the resources to the following location:
https://www.sas.upenn.edu/~sschulze/ursgal_resources/

If you replace the ursgal_resource_url accordingly, everything should work.
The corresponding pull request (#72) is still pending, because due to some dependencies, the tests are failing. 
Sorry that it takes so long, but this should help for now at least.

Best,
Stefan

**Comment by cguetot** [comment]
> we have moved the resources to the following location:
> https://www.sas.upenn.edu/~sschulze/ursgal_resources/
> 
> If you replace the ursgal_resource_url in uparams.py accordingly, everything should work.

Hi Stefan,

On the file  `install_resources.py`,  I setted `uc.params['ursgal_resource_url'] =	'https://www.sas.upenn.edu/~sschulze/ursgal_resources/'` 

And then I ran `python3 install_resources.py `.  However, I still get an error message:
```
Executable for mzidentml_lib_1_6_11 is not available on your system
[ -<HTPP>- ] Downloading files from https://www.sas.upenn.edu/~sschulze/ursgal_resources/ursgal/resources/platform_independent/arc_independent/mzidentml_lib_1_6_11/mzidentml_lib_1_6_11.md ...
[ -<HTPP>- ] 	 WARNING! Could not download https://www.sas.upenn.edu/~sschulze/ursgal_resources/ursgal/resources/platform_independent/arc_independent/mzidentml_lib_1_6_11/mzidentml_lib_1_6_11.md Check your internet connection! 
````

Furthermore, when I try to enter from the browser I get 

````
You don't have permission to access /~sschulze/ursgal_resources/ on this server.

````

**Comment by StSchulze** [comment]
Hi Carlos,

the mzidentml_lib files are indeed missing at the moment, I will add them today. Did any of the other engines work?
I also realized that the md5s changed, so the easiest way to use install_resources would be to checkout my pull request.
Otherwise, downloading the files from https://www.sas.upenn.edu/~sschulze/ursgal_resources/ should work as well, if you use e.g. the get_http_files node in Ursgal. Opening it with a browser doesn't work though, that's true.

**Comment by StSchulze** [comment]
Hi Carlos,

looks good, everything is installed that we are allowed to distribute.
If you want to use any of the other engines, you will need to download them manually. The corresponding links can normally be found in the corresponding wrapper.
And the explanation how to add engines to the resources can be found here: https://ursgal.readthedocs.io/en/latest/faq.html#q-how-do-i-add-an-engine-that-is-not-installed-via-install-resources-py

Let me know if that helps/selves the problem.

**Comment by realperson999** [comment]
Hello,

visiting that url says Forbidden to me. As it attempts to downloaded the first tidbit:

```
Executable for msgfplus_C_mzid2csv_v2017_07_04 is not available on your system
[ -<HTPP>- ] Downloading files from https://www.sas.upenn.edu/~sschulze/ursgal_resources/ursgal/resources/platform_independent/arc_independent/msgfplus_C_mzid2csv_v2017_07_04/msgfplus_C_mzid2csv_v2017_07_04.md ...
[ -<HTPP>- ]     WARNING! Could not download https://www.sas.upenn.edu/~sschulze/ursgal_resources/ursgal/resources/platform_independent/arc_independent/msgfplus_C_mzid2csv_v2017_07_04/msgfplus_C_mzid2csv_v2017_07_04.md Check your internet connection! [ -<HTPP>- ] For OSX, make sure that certificates are installed (Applications/Python 3.x/Install Certificates.command)
```
